var intro_html="";
	intro_html += "		<div id=\"skipnav\" class=\"visuallyhidden\">";
	intro_html += "			<a href=\"#startcontent\" title=\"Skip Navigation\">Skip Navigation<\/a>";
	intro_html += "			<a name=\"top\"><\/a>";
	intro_html += "		<\/div>";
	intro_html += "";
	intro_html += "		<div id=\"printlogo\"><img src=\"images\/FCC-print-logo.jpg\" alt=\"Federal Communications Commission\" \/><\/div>";
	intro_html += "";
	intro_html += "		<div id=\"displayOptions\">";
	intro_html += "			<div class=\"wrapper group\">";
	intro_html += "				<h2>Federal Communications Commission - Electronic Comment Filing System<\/h2>";
	intro_html += "				<img id=\"language\" width=\"55\" height=\"22\" src=\"images\/navLanguageEnglish.png\" alt=\"English\" \/>";
	intro_html += "				<a id=\"displayOptionLink\" class=\"ir\" href=\"#displayOptionPanel\">Display Options<\/a>";
	intro_html += "";
	intro_html += "				<div id=\"displayOptionPanel\" class=\"group\">";
	intro_html += "					<div class=\"right\">";
	intro_html += "						<a id=\"setSmallFont\" href=\"?fontsize=\"><span class=\"smallFont\">a<\/span><\/a> <a id=\"setMediumFont\" href=\"?fontsize=mediumFont\"><span class=\"mediumFont\">a<\/span><\/a> <a id=\"setLargeFont\" href=\"?fontsize=largeFont\"><span class=\"largeFont\">a<\/span><\/a>";
	intro_html += "						<a id=\"setHighContrast\" href=\"?contrast=highContrast\">High Contrast<\/a>";
	intro_html += "						<a id=\"googleTranslate\" href=\"http:\/\/translate.google.com\/translate?prev=hp&hl=en&js=y&u=http%3A%2F%2Ffcc.gov%2Fcomments&sl=en&tl=es&history_state0=\" target=\"_blank\">Translate<\/a>";
	intro_html += "					<\/div>";
	intro_html += "				<\/div>";
	intro_html += "			<\/div>";
	intro_html += "			<!-- \/wrapper -->";
	intro_html += "		<\/div>";
	intro_html += "		<!-- \/displayOptions -->";

	
var header_html="";
	header_html += "				<div id=\"stickynav\"><div id=\"stickywrapper\"><\/div><\/div>";
	header_html += "				<a class=\"logo\" href=\"\/\"><img src=\"images\/logoFCC1.jpg\" alt=\"Federal Communications Commission\" \/><\/a>";
	header_html += "				<div id=\"nav\" class=\"jqueryslidemenu group\">";
	header_html += "					<div id=\"block-menu-primary-links\" class=\"widget block-menu\">";
	header_html += "						<div class=\"widgetContent\">";
	header_html += "							<ul class=\"menu\">";
	header_html += "								<li class=\"\">";
	header_html += "									<a href=\"\/leadership\">The FCC<\/a>";
	header_html += "									<ul>";
	header_html += "									<li  class=\"leaf first \"><a href=\"\/leadership\">Leadership<\/a><\/li>";
	header_html += "									<li  class=\"leaf \"><a href=\"http:\/\/www.fcc.gov\/open-meetings\">Commission Meetings<\/a><\/li>";
	header_html += "									<li  class=\"leaf \"><a href=\"\/encyclopedia\/advisory-committees-fcc\">Advisory Committees<\/a><\/li>";
	header_html += "									<li  class=\"leaf \"><a href=\"\/work\">Jobs &amp; Internships<\/a><\/li>";
	header_html += "									<li  class=\"leaf \"><a href=\"\/finding-people-fcc\">Find People<\/a><\/li>";
	header_html += "									<li  class=\"leaf \"><a href=\"\/contact-us\">Contact Us<\/a><\/li>";
	header_html += "									<li  class=\"leaf \"><a href=\"\/help\">Help<\/a><\/li>";
	header_html += "									<\/ul>";
	header_html += "								<\/li>";
	header_html += "								<li class=\"\">";
	header_html += "									<a href=\"\/what-we-do\">Our Work<\/a>";
	header_html += "									<ul>";
	header_html += "										<li  class=\"leaf first \"><a href=\"\/what-we-do\">What We Do<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/blog\">Blog<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/events\">Events<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/encyclopedia\">FCC Encyclopedia<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/guides\">Guides<\/a><\/li>";
	header_html += "									<\/ul>";
	header_html += "								<\/li>";
	header_html += "								<li class=\"\">";
	header_html += "									<a href=\"\/tools-data\">Tools &amp; Data<\/a>";
	header_html += "									<ul>";
	header_html += "										<li  class=\"leaf first \"><a href=\"\/tools\">Tools<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/developers\">Developers<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"http:\/\/www.fcc.gov\/maps\">Maps<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/data\">Data<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/reports\">Reports<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/working-papers\">Working Papers<\/a><\/li>";
	header_html += "									<\/ul>";
	header_html += "								<\/li>";
	header_html += "								<li class=\"\">";
	header_html += "									<a href=\"\/business-licensing\">Business &amp; Licensing<\/a>";
	header_html += "									<ul>";
	header_html += "										<li  class=\"leaf first \"><a href=\"\/rulemaking\">Rulemaking<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/fcc-items-circulation\">Items on Circulation<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/online-filing\">Online Filing<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/fees\">Fees<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/forms\">Forms<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/documents\">Commission Documents<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/foia\">FOIA<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/exparte\">Ex Parte<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/mergers\">Mergers<\/a><\/li>";
	header_html += "										<li  class=\"leaf \"><a href=\"\/encyclopedia\/small-businesses\">Small Business<\/a><\/li>";
	header_html += "										<li  class=\"leaf last \"><a href=\"\/encyclopedia\/contracting\">Contracting with the FCC<\/a><\/li>";
	header_html += "									<\/ul>";
	header_html += "								<\/li>";
	header_html += "								<li class=\"\">";
	header_html += "									<a href=\"\/bureaus-offices\">Bureaus &amp; Offices<\/a>";
	header_html += "									<ul class=\"fcc_widenav menu\">";
	header_html += "										<div class=\"group\">";
	header_html += "											<li class=\"leaf first\">";
	header_html += "												<div><a href=\"\/consumer-governmental-affairs-bureau\">Consumer &amp; Governmental Affairs<\/a><\/div>";
	header_html += "												<div><a href=\"\/enforcement-bureau\">Enforcement<\/a><\/div>";
	header_html += "												<div><a href=\"\/international-bureau\">International<\/a><\/div>";
	header_html += "												<div><a href=\"\/media-bureau\">Media<\/a><\/div>";
	header_html += "												<div><a href=\"\/public-safety-homeland-security-bureau\">Public Safety &amp; Homeland Security<\/a><\/div>";
	header_html += "												<div><a href=\"\/wireless-telecommunications-bureau\">Wireless Telecommunications<\/a><\/div>";
	header_html += "												<div><a href=\"\/wireline-competition-bureau\">Wireline Competition<\/a><\/div>";
	header_html += "											<\/li>";
	header_html += "											<li class=\"leaf last\">";
	header_html += "												<div><a href=\"\/office-administrative-law-judges\">Administrative Law Judges<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-communications-business-opportunities\">Communications Business Opportunities<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-engineering-technology\">Engineering Technology<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-general-counsel\">General Counsel<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-inspector-general\">Inspector General<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-legislative-affairs\">Legislative Affairs<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-managing-director\">Managing Director<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-media-relations\">Media Relations<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-secretary\">Secretary<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-strategic-planning-policy-analysis\">Strategic Planning &amp; Policy Analysis<\/a><\/div>";
	header_html += "												<div><a href=\"\/office-workplace-diversity\">Workplace Diversity<\/a><\/div>";
	header_html += "											<\/li>";
	header_html += "										<\/div>";
	header_html += "									<\/ul>";
	header_html += "								<\/li>";
	header_html += "							<\/ul>";
	header_html += "						<\/div>";
	header_html += "					<\/div>				";
	header_html += "				<\/div>";
	header_html += "				";
	header_html += "				<div id=\"actionbar\">";
	header_html += "					<a class=\"logo\" href=\"\/\"><img class=\"seal\" src=\"images\/logoFCC2.jpg\" alt=\"Federal Communications Commission\" \/><\/a>";
	header_html += "					<div class=\"logo-extended\">";
	header_html += "						<h1>Electronic Comment Filing System<\/h1>";
	header_html += "					<\/div>";
	header_html += "					<div class=\"searchbox\">";
	header_html += "						<form action=\".\/keyword-search.html\"  accept-charset=\"UTF-8\" method=\"post\" id=\"search_theme_form\">";
	header_html += "							<div>";
	header_html += "								<div id=\"search\" class=\"container-inline\">";
	header_html += "									<div class=\"form-item\" id=\"edit-search-theme-form-1-wrapper\">";
	header_html += "										<label for=\"search_term_input\">Search<\/label>";
	header_html += "										<input type=\"text\" maxlength=\"128\" name=\"search_theme_form\" id=\"search_term_input\" size=\"15\" value=\"\" title=\"Enter the terms you wish to search for.\" class=\"form-text\" \/>";
	header_html += "									<\/div>";
	header_html += "									<input type=\"image\" name=\"submit\" value=\"Search\" id=\"edit-submit\" alt=\"Search\" class=\"form-submit\" src=\"images\/btnSearch.jpg\" \/>";
	header_html += "									<input type=\"hidden\" name=\"form_build_id\" id=\"form-T5ecMA8JQyRhDoxH2vXFToQPVAXi6qEIydfctb6jmW8\" value=\"form-T5ecMA8JQyRhDoxH2vXFToQPVAXi6qEIydfctb6jmW8\"  \/>";
	header_html += "									<input type=\"hidden\" name=\"form_id\" id=\"edit-search-theme-form\" value=\"search_theme_form\"  \/>";
	header_html += "								<\/div>";
	header_html += "							<\/div>";
	header_html += "						<\/form>";
	header_html += "					<\/div>";
	header_html += "					<div class=\"actioncenter filing\">";
	header_html += "						<a id=\"btnTalkToUs\" href=\"\/submit-filing\">ECFS Submission<\/a>";
	header_html += "						<div id=\"navTalkToUs\" class=\"stickyMenu\">";
	header_html += "							<ul>";
	header_html += "								<li class=\"odd\"><a href=\"filing-list.html\">Express Filing<em>Submit a brief public comment<\/em><\/a><\/li>";
	header_html += "								<li class=\"even\"><a href=\"submit-expert-filing.html\">Expert Filing<em>Submit a detailed filing with attachments<\/em><\/a><\/li>";
	header_html += "								<li class=\"odd\"><a href=\"non-docketed-filing.html\">Non-Docketed Filing<em>Submit a non-docketed filing to the FCC inbox with attachments<\/em><\/a><\/li>";
	header_html += "							<\/ul>";
	header_html += "						<\/div>";
	header_html += "					<\/div>";
	header_html += "					<div class=\"actioncenter lookup\">";
	header_html += "						<a id=\"btnLookUp\" href=\"\/comment-lookup\">ECFS Search<\/a>";
	header_html += "						<div id=\"navLookUp\" class=\"stickyMenu\">";
	header_html += "							<ul>";
	header_html += "								<li class=\"odd\"><a href=\"\/filings\">Search for a Filing<em>Search for and view public filings and commission items<\/em><\/a><\/li>";
	header_html += "								<li class=\"even\"><a href=\"\/proceedings\">Search for a Proceeding<em>Find a proceeding (Docket Number, Rulemaking Number, etc.)<\/em><\/a><\/li>";
	header_html += "								<li class=\"odd\"><a href=\"\/status\">Check your Filing Status<em>Use your confirmation number to check the status of a filing online. <\/em><\/a><\/li>";
	header_html += "							<\/ul>";
	header_html += "						<\/div>";
	header_html += "					<\/div>";
	header_html += "					<div class=\"actioncenter links\">";
	header_html += "						<div id=\"nav\" class=\"jqueryslidemenu group left\">";
	header_html += "							<div class=\"widget\">";
	header_html += "								<div class=\"widgetContent help-menu\">";
	header_html += "									<ul class=\"menu\">";
	header_html += "										<li class=\"\">";
	header_html += "											<input type=\"image\" name=\"submit\" value=\"Search\" id=\"help-menu\"  alt=\"Help\" class=\"icon-menu-btn\" src=\"images\/help_menu_icon.png\"\/>";
	header_html += "											<ul>";
	header_html += "												<li  class=\"leaf \"><a href=\"mailto:ecfshelp@fcc.gov\">ECFS Help<\/a><\/li>";
	header_html += "												<li  class=\"leaf first \"><a href=\"\/leadership\">ECFS User Manual<\/a><\/li>";
	header_html += "												<li  class=\"leaf \"><a href=\"\/contact-us\">FCC Contact Us<\/a><\/li>";
	header_html += "												<li  class=\"leaf \"><a href=\"\/help\">FCC Help<\/a><\/li>";
	header_html += "												<li  class=\"leaf \"><a href=\"guidelines.html\">Filing Guidelines<\/a><\/li>";
	header_html += "												<li  class=\"leaf \"><a href=\"/help/support-information-online-filing\">Filing Support<\/a><\/li>";
	header_html += "												<li  class=\"leaf\"><a href=\"\/encyclopedia\/site-map-transitionfccgov\">Site Map<\/a><\/li>";	
	header_html += "												<li  class=\"leaf last\"><a href=\"\http://www.fcc.gov/cgi-bin/EFBoards/systemstatus.cgi?index_t=../../pub/e-file/messages/ECFS.html\">System Status<\/a><\/li>";
	header_html += "											<\/ul>";
	header_html += "										<\/li>";
	header_html += "									<\/ul>";
	header_html += "								<\/div>";
	header_html += "							<\/div>";
	header_html += "						<\/div>";
	header_html += "						<div id=\"nav\" class=\"jqueryslidemenu group right\">";
	header_html += "							<div class=\"widget\">";
	header_html += "								<div class=\"widgetContent fcc-menu\">";
	header_html += "									<ul class=\"menu\">";
	header_html += "										<li class=\"\">";
	header_html += "											<input type=\"image\" name=\"submit\" value=\"Search\" id=\"fcc-menu\"  alt=\"Search\" class=\"icon-menu-btn\" src=\"images\/three_line_menu.png\" \/>";
	header_html += "											<ul>";
	header_html += "												<li  class=\"leaf first \"><a href=\"\/leadership\" title=\"\">The FCC<\/a><\/li>";
	header_html += "												<li  class=\"leaf \"><a href=\"\/what-we-do\" title=\"\">Our Work<\/a><\/li>";
	header_html += "												<li  class=\"leaf \"><a href=\"\/tools-data\" title=\"\">Tools &amp; Data<\/a><\/li>";
	header_html += "												<li  class=\"leaf \"><a href=\"\/business-licensing\" title=\"\">Business &amp; Licensing<\/a><\/li>";
	header_html += "												<li  class=\"leaf last\"><a href=\"\/bureaus-offices\" title=\"\">Bureaus &amp; Offices<\/a><\/li>";
	header_html += "											<\/ul>";
	header_html += "										<\/li>";
	header_html += "									<\/ul>";
	header_html += "								<\/div>";
	header_html += "							<\/div>";
	header_html += "						<\/div>";
	header_html += "					<\/div>";
	header_html += "				<\/div>";
	
	var sidebar_html = "";
	sidebar_html += "			<div class='widget block-block' id='block-block-39'>";
	sidebar_html += "				<h2 class='widgetTitle'>Search Public Comments</h2>";
	sidebar_html += "				<div class='widgetContent'><p>Search Proceeding Comments.</p>";
	sidebar_html += "					<p style='text-align: center;'>";
	sidebar_html += "						<a href='http://fjallfoss.fcc.gov/ecfs/' target='_blank'><img alt='Find Comments' src='' /></a>";
	sidebar_html += "					</p>";
	sidebar_html += "				</div>";
	sidebar_html += "			</div>";
	sidebar_html += "			<div class='widget block-block' id='block-block-28'>";
	sidebar_html += "				<h2 class='widgetTitle'>Filing and Duplicating</h2>";
	sidebar_html += "				<div class='widgetContent'>";
	sidebar_html += "					<p>Get instructions for filing paper documents to the Office of the Secretary.</p>";
	sidebar_html += "					<p style='text-align: center;'>";
	sidebar_html += "						<a href='./guidelines.html' target='_blank'><img alt='Filing Guidelines' src='' /></a>";
	sidebar_html += "					</p>";
	sidebar_html += "					<p>Learn about the FCC's Copy Contractor now providing duplicating and research services.</p>";
	sidebar_html += "					<p style='text-align: center;'>";
	sidebar_html += "						<a href='https://apps.fcc.gov/edocs_public/attachmatch/DOC-248457A1.pdf' target='_blank'><img alt='Best Copy and Printing, Inc.' src='' /></a>";
	sidebar_html += "					</p>";
	sidebar_html += "				</div>";
	sidebar_html += "			</div>";
	sidebar_html += "			<div class='widget block-block' id='block-block-41'>";
	sidebar_html += "				<h2 class='widgetTitle'>More Information</h2>";
	sidebar_html += "				<div class='widgetContent'>";
	sidebar_html += "					<p style='text-align: center;'>";
	sidebar_html += "						<a href='http://www.fcc.gov/cgi-bin/EFBoards/systemstatus.cgi?index_t=../../pub/e-file/messages/ECFS.html'><img src='' alt='ECFS System Status' /></a><br>";
	sidebar_html += "						<a href='http://www.fcc.gov/help/support-information-online-filing'><img src='' alt='E-Filing Support Information' /></a><br>";
	sidebar_html += "						<a href='http://www.fcc.gov/cgb/'><img src='' alt='Consumer and Governmental Affairs Bureau' /></a>";
	sidebar_html += "					</p>";
	sidebar_html += "				</div>";
	sidebar_html += "			</div>";
	
var footer_html="";
	footer_html += "				<div id=\"sealContainer\" class=\"left\">";
	footer_html += "					<ul class=\"seal\">";
	footer_html += "						<li>Federal Communications Commission<\/li>";
	footer_html += "						<li>445 12th Street SW, Washington, DC 20554<\/li>";
	footer_html += "						<li>Phone: 1-888-225-5322<\/li>";
	footer_html += "						<li>TTY:  1-888-835-5322<\/li>";
	footer_html += "						<li>Videophone: 1-844-432-2275<\/li>";
	footer_html += "						<li>Fax: 1-866-418-0232<\/li>";
	footer_html += "						<li><a href=\"\/contact-us\">Contact Us<\/a><\/li>";
	footer_html += "					<\/ul>";
	footer_html += "				<\/div>";
	footer_html += "				<!-- \/sealContainer -->";
	footer_html += "				<div id=\"metaLinks\" class=\"right\">";
	footer_html += "					<div id=\"block-\" class=\"widget block-block block-60 footer_meta_links\">";
	footer_html += "						<div>";
	footer_html += "							<ul>";
	footer_html += "								<li><a href=\"\/encyclopedia\/privacy-policy\">Privacy Policy<\/a><\/li>";
	footer_html += "								<li><a href=\"\/comment-policy\">Moderation Policy<\/a><\/li>";
	footer_html += "								<li><a href=\"\/encyclopedia\/website-notices\">Website Policies &amp; Notices<\/a><\/li>";
	footer_html += "								<li><a href=\"\/encyclopedia\/required-plug-ins-players-and-readers\">Required Browser &amp; Plug-ins<\/a><\/li>";
	footer_html += "								<li><a href=\"\/foia\">FOIA<\/a><\/li>";
	footer_html += "								<li><a href=\"\/encyclopedia\/no-fear-act-data\">No Fear Act Data<\/a><\/li>";
	footer_html += "							<\/ul>";
	footer_html += "";
	footer_html += "							<ul>";
	footer_html += "								<li><a href=\"\/digitalstrategy\">FCC Digital Strategy<\/a><\/li>";
	footer_html += "								<li><a href=\"\/open\">Open Government Directive<\/a><\/li>";
	footer_html += "								<li><a href=\"\/encyclopedia\/plain-writing-fcc\">Plain Writing Act<\/a><\/li>";
	footer_html += "								<li><a href=\"\/encyclopedia\/american-recovery-and-reinvestment-act-2009\">2009 Recovery and Reinvestment Act<\/a><\/li>";
	footer_html += "								<li><a href=\"\/rss\">RSS Feeds &amp; Email Updates<\/a><\/li>";
	footer_html += "								<li><a href=\"\/encyclopedia\/disability-rights-office\">Disability Rights<\/a><\/li>";
	footer_html += "								<!--<li><a href=\"\/office-inspector-general\">Office of Inspector General<\/a><\/li>-->";
	footer_html += "							<\/ul>";
	footer_html += "						<\/div>";
	footer_html += "					<\/div>				";
	footer_html += "				<\/div>";
	


